### PR TITLE
hardware: Add labelled image of device nRF52840-DK

### PR DESCRIPTION
**Pull request by Hoverbear**
Adds a labelled image for the nRF52840.

### CODE REVIEW

**Comment by Lotterleben** [comment]
Love this! Thank you so much. Gonna leave this open so @Mirabellensaft and @japaric see it but it's an ✅ from me :)

**Comment by Mirabellensaft** [comment]
This is totally awesome! we should just check that including this image is legally ok.

**Comment by Hoverbear** [comment]
Okay!

Legal things:

* I did take this and I am very happy to release it under any license of your choosing.
* I am the owner/operator of my company, acting of my own will and as an agent of my company.
* My company purchased, and owns these boards.

Thanks. :)

**Comment by jamesmunns** [comment]
Thanks @Hoverbear!

**Pull request merged**
