### PR TITLE
Add `--erase-all` to `probe-run` invocations

### PR DESCRIPTION
**Pull request by Urhengulas**
Newer models of the nrf52840 need this in order to flash.

### CODE REVIEW

**Comment by Urhengulas** [comment]
@amanjeev Can you please test if now works for you out of the box?

**Review by amanjeev — APPROVED** [review]
confirmed that the [tooling check section of the book](https://embedded-trainings.ferrous-systems.com/tooling-check.html) work. as in, the hello.rs prints hello in both new and old board.

**Comment by amanjeev** [comment]
@Urhengulas thank you! could you please link to probe-run fix PR here as well please for the sake of connecting the two?

**Comment by Urhengulas** [comment]
Sure, https://github.com/knurling-rs/probe-run/pull/380

**Pull request merged**
